INSERT INTO users (id, email, name, password)
VALUES ('2b6f1c2e-8c8f-4f3a-9d9b-1c2a9f1e0a11',
        'alice@example.com',
        'Alice Silva',
        '$2a$12$jZputfCehMEwBxkgX/jym.Xs5hX4vPsOckSmxGTUljDjfmN1icuoy'),
       ('9e4a7d3b-6c2a-4a8e-9f55-3d1a8b7c2e22',
        'bob@example.com',
        'Bob Santos',
        '$2a$12$jZputfCehMEwBxkgX/jym.Xs5hX4vPsOckSmxGTUljDjfmN1icuoy');

INSERT INTO ideas (id, created_at, title, summary, description, tags, author_id)
VALUES ('a1c2d3e4-1111-4aaa-bbbb-aaaaaaaaaaaa',
        (NOW() + interval '1 day'),
        'Plataforma de estudos',
        'Organização de estudos online',
        'Aplicação web para organizar estudos, metas e progresso.',
        ARRAY ['education', 'productivity'],
        '2b6f1c2e-8c8f-4f3a-9d9b-1c2a9f1e0a11'),
       ('a1c2d3e4-2222-4aaa-bbbb-bbbbbbbbbbbb',
        (NOW() + interval '2 day'),
        'Gerenciador de hábitos',
        'Acompanhamento de hábitos',
        'Sistema para criar e monitorar hábitos diários.',
        ARRAY ['habits', 'self-improvement'],
        '2b6f1c2e-8c8f-4f3a-9d9b-1c2a9f1e0a11'),
       ('a1c2d3e4-3333-4aaa-bbbb-cccccccccccc',
        (NOW() + interval '3 day'),
        'App de anotações',
        'Notas rápidas',
        'Aplicativo para criar e organizar anotações.',
        ARRAY ['notes', 'productivity'],
        '2b6f1c2e-8c8f-4f3a-9d9b-1c2a9f1e0a11');

INSERT INTO ideas (id, created_at, title, summary, description, tags, author_id)
VALUES ('f9e8d7c6-4444-4bbb-aaaa-dddddddddddd',
        (NOW() + interval '4 day'),
        'Controle financeiro',
        'Finanças pessoais',
        'Sistema para controle de gastos mensais.',
        ARRAY ['finance', 'personal'],
        '9e4a7d3b-6c2a-4a8e-9f55-3d1a8b7c2e22'),
       ('f9e8d7c6-5555-4bbb-aaaa-eeeeeeeeeeee',
        (NOW() + interval '5 day'),
        'Agenda de serviços',
        'Agendamento online',
        'Plataforma de agendamento para serviços.',
        ARRAY ['saas', 'scheduling'],
        '9e4a7d3b-6c2a-4a8e-9f55-3d1a8b7c2e22'),
       ('f9e8d7c6-6666-4bbb-aaaa-ffffffffffff',
        (NOW() + interval '6 day'),
        'Marketplace local',
        'Comércio regional',
        'Marketplace focado em pequenos negócios locais.',
        ARRAY ['marketplace', 'local-business'],
        '9e4a7d3b-6c2a-4a8e-9f55-3d1a8b7c2e22');

